app.py
from factory import create_app

application = create_app()

blueprints/__init__.py
from blueprints import standalone, id, flair, schematics

blueprint_packages = [
    standalone,
    id,
    flair,
    schematics
]

blueprints = [p.blueprint for p in blueprint_packages]

blueprints/api/__init__.py
from flask_restful import Api

api = Api(prefix="/api")

blueprints/flair/__init__.py
from flask import Blueprint, render_template, request, session, redirect, url_for
import hashlib
import os
import praw
import urllib

from blueprints.id import mc_auth

blueprint = Blueprint('flair', __name__, url_prefix='/flair')
blueprint.config = {}

bot = None
oauth = None


@blueprint.record
def record_config(setup_state):
    app = setup_state.app
    blueprint.config = dict([(key, value) for (key, value) in app.config.iteritems()])

    global bot
    bot = praw.Reddit(
        user_agent='script:bromweb.flair.mod:v1.0 (by /u/williammck)',
        client_id=blueprint.config.get('REDDIT_BOT_CLIENT_ID'),
        client_secret=blueprint.config.get('REDDIT_BOT_CLIENT_SECRET'),
        username=blueprint.config.get('REDDIT_BOT_USERNAME'),
        password=blueprint.config.get('REDDIT_BOT_PASSWORD'),
    )

    global oauth
    oauth = praw.Reddit(
        user_agent='web:bromweb.flair.client:v1.0 (by /u/williammck)',
        client_id=blueprint.config.get('REDDIT_CLIENT_ID'),
        client_secret=blueprint.config.get('REDDIT_CLIENT_SECRET'),
        redirect_uri=blueprint.config.get('REDDIT_REDIRECT_URI')
    )


@blueprint.route('/')
def index():
    state = hashlib.md5(os.urandom(24)).hexdigest()
    url = oauth.auth.url(['identity'], state, 'temporary')
    return render_template('flair/index.html', url=url)


@blueprint.route('/callback')
def callback():
    if 'error' in request.args:
        return redirect(url_for('.index'))

    code = request.args.get('code')

    oauth.auth.authorize(code)

    reddit_username = oauth.user.me().name
    session['reddit_username'] = reddit_username

    oauth.read_only = True

    return redirect(url_for('.menu'))


@blueprint.route('/menu')
def menu():
    if 'reddit_username' not in session:
        return redirect(url_for('.index'))

    return render_template('flair/menu.html')


@blueprint.route('/auth')
def auth():
    return mc_auth(url_for('.confirm'))


@blueprint.route('/confirm')
def confirm():
    if 'reddit_username' not in session:
        return redirect(url_for('index'))
    if 'minecraft_username' not in session:
        return redirect(url_for('minecraft_auth'))

    reddit_username = session['reddit_username']
    minecraft_username = session['minecraft_username']

    if reddit_username.lower() == minecraft_username.lower():
        same_username = True
    else:
        same_username = False

    return render_template('flair/confirm.html', same_username=same_username)


@blueprint.route('/retry')
def retry():
    session.clear()
    return redirect(url_for('.index'))


@blueprint.route('/submit')
def submit():
    if 'reddit_username' not in session:
        return redirect(url_for('.index'))
    if 'minecraft_username' not in session:
        return redirect(url_for('.auth'))

    reddit_username = session['reddit_username']
    minecraft_uuid = session['minecraft_uuid']
    minecraft_username = session['minecraft_username']

    subreddit = bot.subreddit(blueprint.config.get('REDDIT_SUBREDDIT'))

    minecraft_head_url = 'https://crafatar.com/avatars/' + minecraft_uuid + '?size=32'
    minecraft_head_path, headers = urllib.urlretrieve(minecraft_head_url)
    subreddit.stylesheet.upload(minecraft_username, minecraft_head_path)

    flair_css = '.flair-' + minecraft_username + ' { background: url(%%' + minecraft_username + '%%) }\n'
    stylesheet = subreddit.stylesheet().stylesheet
    if flair_css not in stylesheet:
        stylesheet = stylesheet.replace(
            blueprint.config.get('REDDIT_CSS_MARKER'),
            flair_css + blueprint.config.get('REDDIT_CSS_MARKER')
        )
        subreddit.stylesheet.update(stylesheet, 'Added flair for ' + minecraft_username)

    if reddit_username.lower() == minecraft_username.lower():
        flair_text = ''
    else:
        flair_text = minecraft_username

    subreddit.flair.set(reddit_username, flair_text, minecraft_username)
    return redirect(url_for('.done'))


@blueprint.route('/remove')
def remove():
    if 'reddit_username' not in session:
        return redirect(url_for('.index'))

    reddit_username = session['reddit_username']

    subreddit = bot.subreddit(blueprint.config.get('REDDIT_SUBREDDIT'))
    subreddit.flair.delete(reddit_username)

    return redirect(url_for('.done'))


@blueprint.route('/done')
def done():
    if 'reddit_username' not in session:
        return redirect(url_for('.index'))

    session.clear()
    return render_template('flair/done.html')

blueprints/id/__init__.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from flask_restful import Resource
from flask_restful.reqparse import RequestParser
import redis

from blueprints.api import api

blueprint = Blueprint('id', __name__, url_prefix='/id')
r = redis.StrictRedis(host='localhost', port=6379, db=0)


@blueprint.route('/auth')
def auth():
    if 'X-Forwarded-For' in request.headers:
        ip = request.headers['X-Forwarded-For']
    else:
        ip = request.remote_addr

    minecraft = check_authenticated_ip(ip)
    if minecraft:
        r.delete('brom:id:mc_auth:' + ip)

        session['minecraft_uuid'] = minecraft['uuid']
        session['minecraft_username'] = minecraft['display_name']
        session['minecraft_ip'] = minecraft['ip_address']

        redirect_url = session.pop('mc_auth_callback_url', None)
        return redirect(redirect_url)

    else:
        return render_template('id/auth.html', ip=ip)


def mc_auth(callback_url):
    session['mc_auth_callback_url'] = callback_url
    return redirect(url_for('id.auth'))


def check_authenticated_ip(ip):
    info = r.hgetall('brom:id:mc_auth:' + ip)

    return info


class MinecraftAuthentication(Resource):
    def get(self):
        if 'X-Forwarded-For' in request.headers:
            ip = request.headers['X-Forwarded-For']
        else:
            ip = request.remote_addr
        result = check_authenticated_ip(ip)

        return {'verified': bool(result)}

api.add_resource(MinecraftAuthentication, '/id/auth')

blueprints/schematics/__init__.py
from flask import Blueprint, render_template, redirect, url_for
from flask_wtf import FlaskForm, RecaptchaField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from os import listdir
from os.path import isfile, join
from werkzeug.utils import secure_filename
from wtforms import HiddenField, SubmitField
import os

blueprint = Blueprint('schematics', __name__, url_prefix='/schematics')
blueprint.config = {}


@blueprint.record
def record_config(setup_state):
    app = setup_state.app
    blueprint.config = dict([(key, value) for (key, value) in app.config.iteritems()])


class UploadForm(FlaskForm):
    schematic = FileField('Schematic to upload', validators=[
        FileRequired(),
        FileAllowed(['schematic'], 'Schematics only!')
    ])
    recaptcha = RecaptchaField()
    submit = SubmitField('Upload')


class RemoveForm(FlaskForm):
    filename = HiddenField('Schematic to delete')
    submit = SubmitField('Delete')


@blueprint.route('/')
def index():
    path = blueprint.config.get('SCHEMATICS_PATH')
    os.chdir(path)

    upload_form = UploadForm()
    remove_form = RemoveForm()

    files = filter(os.path.isfile, os.listdir(path))
    files.sort(key=os.path.getmtime, reverse=True)
    return render_template('schematics/index.html', files=files, upload_form=upload_form, remove_form=remove_form)


@blueprint.route('/upload', methods=['POST'])
def upload():
    path = blueprint.config.get('SCHEMATICS_PATH')
    form = UploadForm()
    if form.validate_on_submit():
        filename = secure_filename(form.schematic.data.filename)
        form.schematic.data.save(path + filename)
    return redirect(url_for('.index'))


@blueprint.route('/remove', methods=['POST'])
def remove():
    path = blueprint.config.get('SCHEMATICS_PATH')
    form = RemoveForm()
    files = [f for f in listdir(path) if isfile(join(path, f))]

    filename = form.filename.data
    if filename not in files:
        return redirect(url_for('.index'))

    os.renames(path + filename, path + 'deleted/' + filename)
    return redirect(url_for('.index'))

blueprints/standalone/__init__.py
from flask import Blueprint, render_template

blueprint = Blueprint('standalone', __name__, url_prefix='/')


@blueprint.route('/')
def index():
    return render_template('standalone/index.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Brom</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.5/css/bootstrap.min.css">
    <style>
      html {
        min-height: 100%;
      }
      body {
        background-color: #222222;
        background-image: url('{{ url_for('static', filename='img/background.jpg') }}');
        background-position: center center;
        background-size: cover;
      }
      body.no-bg {
        background-image: none;
      }
      .card {
        color: #ffffff;
        background-color: rgba(0, 0, 0, 0.7);
        border-color: rgba(0, 0, 0, 0.7);
      }
    </style>
  </head>
  <body{%- if no_bg %} class="no-bg"{% endif %}>
    <nav class="navbar navbar-full navbar-dark bg-inverse">
      <a class="navbar-brand" href="{{ url_for('standalone.index') }}">Brom</a>
      <ul class="nav navbar-nav">
        <li class="nav-item{%- if request.endpoint == 'standalone.index' %} active{% endif %}">
          <a class="nav-link" href="{{ url_for('standalone.index') }}">Servers{%- if request.endpoint == 'standalone.index' %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
        <li class="nav-item{%- if request.blueprint == 'flair' %} active{% endif %}">
          <a class="nav-link" href="{{ url_for('flair.index') }}">Flair{%- if request.blueprint == 'flair' %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
        <li class="nav-item{%- if request.blueprint == 'schematics' %} active{% endif %}">
          <a class="nav-link" href="{{ url_for('schematics.index') }}">Planning Schematics{%- if request.blueprint == 'schematics' %} <span class="sr-only">(current)</span>{% endif %}</a>
        </li>
      </ul>
    </nav>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-8 offset-sm-2 text-xs-center">
          <div class="card card-inverse">
            <div class="card-block">
              <h1><img src="{{ url_for('static', filename='img/logo.png') }}"></h1>
              {% block header_content %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8 offset-sm-2 text-xs-center">
          <div class="card card-inverse">
            <div class="card-block">
              {% block content %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8 offset-sm-2 text-xs-center">
          <div class="card card-inverse">
            <div class="card-block">
              Issues? Contact <a href="https://www.reddit.com/message/compose?to=williammck">William McKinnerney</a>.
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.5/js/bootstrap.js"></script>
    {% block javascript %}{% endblock %}
  </body>
</html>

templates/flair/confirm.html
{% extends 'base.html' %}
{% block header_content %}
  <br>
  <h4>Flair</h4>
{% endblock %}
{% block content %}
  <p>
    Reddit username: {{ session['reddit_username'] }}<br>
    Minecraft username: {{ session['minecraft_username'] }}<br>
    Minecraft head: <img src="https://crafatar.com/avatars/{{ session['minecraft_uuid'] }}?size=32" style="border: 1px solid #ffffff;">
  </p>
  <a class="btn btn-danger" href="{{ url_for('.retry') }}">Retry</a>
  <a class="btn btn-success" href="{{ url_for('.submit') }}">Submit!</a>
{% endblock %}

templates/flair/done.html
{% extends 'base.html' %}
{% block header_content %}
  <br>
  <h4>Flair</h4>
{% endblock %}
{% block content %}
  <p>We're done here.</p>
  <a class="btn btn-primary" href="{{ url_for('.index') }}">Do it again!</a>
{% endblock %}

templates/flair/error.html
{% extends 'base.html' %}
{% block header_content %}
  <br>
  <h4>Flair</h4>
{% endblock %}
{% block content %}
  <p>{{ error }}</p>
  <a class="btn btn-primary" href="{{ url_for('.index') }}">Retry</a>
{% endblock %}

templates/flair/index.html
{% extends 'base.html' %}
{% block header_content %}
  <br>
  <h4>Flair</h4>
{% endblock %}
{% block content %}
  <a class="btn btn-primary" href="{{ url }}">Login with Reddit</a>
{% endblock %}

templates/flair/menu.html
{% extends 'base.html' %}
{% block header_content %}
  <br>
  <h4>Flair</h4>
{% endblock %}
{% block content %}
  <a class="btn btn-primary" href="{{ url_for('.auth') }}">Add/Update Flair</a>
  <a class="btn btn-danger" href="{{ url_for('.remove') }}">Remove Flair</a>
  <br><br>
  <a class="btn btn-info" href="{{ url_for('.done') }}">Cancel</a>
{% endblock %}

templates/flair_confirm.html
{% extends 'layout.html' %}
{% block content %}
  <p>
    Reddit username: {{ session['reddit_username'] }}<br>
    Minecraft username: {{ session['minecraft_username'] }}<br>
    Minecraft head: <img src="https://crafatar.com/avatars/{{ session['minecraft_uuid'] }}?size=32" style="border: 1px solid #ffffff;">
  </p>
  <a class="btn btn-danger" href="{{ url_for('flair_retry') }}">Retry</a>
  <a class="btn btn-success" href="{{ url_for('flair_submit') }}">Submit!</a>
{% endblock %}

templates/id/auth.html
{% extends 'base.html' %}
{% block header_content %}
  <br>
  <h4>BromID</h4>
{% endblock %}
{% block content %}
  Waiting for connection to identification server...<br>
  Connect to <code>id.brom.io</code> with the Minecraft user you want as your flair.
{% endblock %}
{% block javascript %}
  <script>
    function do_polling() {
      $.ajax({
        url: "{{ url_for('minecraftauthentication') }}",
        cache: false,
        success: function(data, status, event) {
            if(data["verified"] == true) {
                document.location.reload(true);
            }
        },
        complete: function(event, status) {
            window.setTimeout(do_polling, 3000);
        }
      })
    }
    do_polling();
  </script>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block content %}
  <a class="btn btn-primary" href="{{ url }}">Login with Reddit</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Brom</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css">
    <style>
      html {
        min-height: 100%;
      }
      body {
        background-image: url('{{ url_for('static', filename='img/background.jpg') }}');
        background-position: center center;
        background-size: cover;
      }
      .card {
        background-color: rgba(0, 0, 0, 0.7);
        border-color: rgba(0, 0, 0, 0.7);
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-full navbar-dark bg-inverse">
      <a class="navbar-brand" href="https://brom.io">Brom</a>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="https://brom.io">Servers</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('index') }}">Flair <span class="sr-only">(current)</span></a>
        </li>
      </ul>
    </nav>
    <br>
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-xs-center">
          <div class="card card-inverse">
            <div class="card-block">
              <h1><img src="{{ url_for('static', filename='img/logo.png') }}"></h1>
              <br>
              <h3 class="card-title">Flair</h3>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-xs-center">
          <div class="card card-inverse">
            <div class="card-block">
              <div class="card-text">
                {% block content %}{% endblock %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-xs-center">
          <div class="card card-inverse">
            <div class="card-block">
              <p class="card-text">
                Issues? Contact <a href="https://www.reddit.com/message/compose?to=williammck">William McKinnerney</a>.
                Avatars provided by <a href="https://crafatar.com">Crafatar</a>.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>
  </body>
</html>

templates/schematics/index.html
{% extends 'base.html' %}
{% set no_bg = true %}
{% block header_content %}
  <br>
  <h4>Planning Schematics</h4>
{% endblock %}
{% block content %}
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#uploadModal">
    Upload Schematic
  </button>
  <br>
  <br>
  <div class="table-responsive">
    <table class="table table-inverse table-bordered text-xs-left">
      <thead>
        <tr>
          <th>Filename</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for file in files %}
          <tr>
            <td><a href="http://p.brom.io/schematics/{{ file }}">{{ file }}</a></td>
            <td><a href="#removeModal" data-toggle="modal" data-filename="{{ file }}">Remove</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}
{% block javascript %}
  <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form action="{{ url_for('.upload') }}" method="POST" enctype="multipart/form-data">
          {{ upload_form.csrf_token }}
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="uploadModalLabel">Upload Schematic</h4>
          </div>
          <div class="modal-body">
            <fieldset class="form-group">
              {{ upload_form.schematic.label }}
              {{ upload_form.schematic(class='form-control-file') }}
            </fieldset>
            {{ upload_form.recaptcha }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            {{ upload_form.submit(class='btn btn-primary') }}
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="modal fade" id="removeModal" tabindex="-1" role="dialog" aria-labelledby="removeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form action="{{ url_for('.remove') }}" method="POST" enctype="multipart/form-data">
          {{ remove_form.csrf_token }}
          {{ remove_form.filename }}
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h4 class="modal-title" id="removeModalLabel">Remove Schematic</h4>
          </div>
          <div class="modal-body">
            <p>Are you sure you want to remove the schematic "<span class="filename"></span>"?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            {{ remove_form.submit(class='btn btn-danger') }}
          </div>
        </form>
      </div>
    </div>
  </div>
  <script>
    $('#removeModal').on('show.bs.modal', function (event) {
      var link = $(event.relatedTarget);
      var filename = link.data('filename');
      var modal = $(this);
      modal.find('.modal-content #filename').val(filename);
      modal.find('.modal-body .filename').text(filename);
    })
  </script>
{% endblock %}

templates/standalone/index.html
{% extends 'base.html' %}
{% block header_content %}
  <p>
    Come join us: <code>p.nerd.nu</code><br>
    X: -65, Z: 1770
  </p>
  <a class="btn btn-primary" href="https://reddit.com/r/brom/">Subreddit</a>
  <a class="btn btn-primary" href="https://webchat.gamesurge.net/?nick=Bromulan...&channels=Brom&prompt=1">IRC</a>
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col-sm-6">
      <h4>Planning</h4>
      <p>Connect: <code>p.brom.io</code></p>
      <a class="btn btn-primary btn-sm" href="http://p.brom.io/">Cartograph</a>
    </div>
    <div class="col-sm-6">
      <h4>Museum</h4>
      <p>Connect: <code>m.brom.io</code></p>
      <a class="btn btn-primary btn-sm" href="http://m.brom.io/">Cartograph</a>
    </div>
  </div>
{% endblock %}